# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: kb
email: dsmith73@gmail.com
author: Dan Smith
description: > # this means to ignore newlines until "baseurl:"
  Simple document management project to be used as static site reference 
  from monitoring tools (prometheus in this scenario) to dynamically 
  access site content based on deployed tags.

# DO NOT CHANGE THE LINE OF THIS FILE without editing .circleci/circle_urls.sh
baseurl: "/kb" # the subpath of your site

url: "https://101101.github.io" # the base hostname & protocol for the site

# Social (First three Required)
repo: "https://github.com/101101/kb"
github_user: "101101"
github_repo: "kb"

# Optional
twitter: dsmith73
linkedin: dsmith73
dockerhub: dsmith73

# Should there be feedback buttons at the bottom of pages?
feedback: true

# Link to a privacy policy in footer, uncomment and define if wanted
# privacy: https://domain.com/privacy

# google-analytics: UA-XXXXXXXXXX

logo_pixels: 34
color: "0f3b61"
# color: "#30638e"  # original color

# Build settings
markdown: kramdown

tag_color: primary # danger, success, warning, primary, info, secondary
accentColor: red # purple, green, etc.
themeColor: red # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false
highlighter: rouge

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
      
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      
  - scope:
      path: "_docs/noc"
      type: "noc"
    values:
      layout: "page"
      category: "noc"
      tags: "noc"
      
  - scope:
      path: "_docs/infra"
      type: "infra"
    values:
      layout: "page"
      category: "infra"
      tags: "infra"
      
  - scope:
      path: "_docs/product-x"
      type: "product-x"
    values:
      layout: "page"
      category: "product-x"
      tags: "product-x"
      
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
